title: Jay Torres # your name (or website title) here
logo: "D3A6A156-1CD6-4223-88A6-FB05B67DD181.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  hi i'm jay :)

  i like writing words that people can relate to. as a kid i thought this meant i'd be an author or journalist and travel the world and be under a really mysterious pen name like Lemony Sniket or R.L Stein. 
  but now i write words in apps and websites and sit at a computer for 12 hours a day. 
  which is cool too.
  <br><br>
  other than typing words i enjoy video games, horror, reading, and drawing poorly
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal

