title: Jay Torres # your name (or website title) here
logo: "D3A6A156-1CD6-4223-88A6-FB05B67DD181.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  I like writing words that people can relate to. As a kid, I thought this meant I'd be an author traveling the world under a really mysterious pen name. 
  Instead, I write words for apps and websites and sit at a computer for 12 hours a day. 
  <br><br>Which is cool too.
  <br><br>
I also enjoy video games, horror, reading, and drawing poorly. 
  <br><br>
  I'm currently a writer at <a href="https://discord.com/">Discord</a> where I write and edit user-facing copy, updates, social posts, and more. 
  
theme: jekyll-theme-minimal

